ingress:
  - https://tiltakspenger-soknad.intern.dev.nav.no
TILTAKSPENGER_SOKNAD_API_URL: http://tiltakspenger-soknad-api
NEXT_PUBLIC_TELEMETRY_URL: https://telemetry.ekstern.dev.nav.no/collect
unleash:
  environment: development
  url: https://tiltakspenger-unleash-api.nav.cloud.nais.io/api
dekorator:
  env: dev
