apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-soknad
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  image: {{ image }}
  port: 3000
  startup:
    path: {{ probes.isAlive }}
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 60 # 5 + 60 × 5 s ≈ 5 min oppstartsvindu
    timeout: 3
  liveness:
    path: {{ probes.isAlive }}
    periodSeconds: 10
    failureThreshold: 3
    timeout: 3
  readiness:
    path: {{ probes.isReady }}
    periodSeconds: 5
    failureThreshold: 1
    timeout: 3
  env:
      - name: TILTAKSPENGER_SOKNAD_API_URL
        value: {{ TILTAKSPENGER_SOKNAD_API_URL }}
      - name: NEXT_PUBLIC_TELEMETRY_URL
        value: {{ NEXT_PUBLIC_TELEMETRY_URL }}
      - name: DEKORATOR_ENV
        value: {{ dekorator.env }}
  ingresses:
    - {{ ingress }}
  replicas:
    min: 2
    max: 2
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tiltakspenger-soknad-api
        - application: nav-dekoratoren
          namespace: personbruker
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
