apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-soknad
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  image: {{ image }}
  port: 3000
  env:
      - name: TILTAKSPENGER_SOKNAD_API_URL
        value: {{ TILTAKSPENGER_SOKNAD_API_URL }}
      - name: NEXT_PUBLIC_TELEMETRY_URL
        value: {{ NEXT_PUBLIC_TELEMETRY_URL }}
      - name: UNLEASH_SERVER_API_URL
        value: {{ unleash.url }}
      - name: DEKORATOR_ENV
        value: {{ dekorator.env }}
  envFrom:
    - secret: tiltakspenger-soknad-unleash-secrets
  ingresses:
    - {{ ingress }}
  replicas:
    min: 2
    max: 2
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tiltakspenger-soknad-api
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: tiltakspenger-unleash-api.nav.cloud.nais.io
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
