apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: tiltakspenger-soknad
    namespace: tpts
    labels:
        team: tpts
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: '20m'
spec:
    image: { { image } }
    port: 3000
    env:
        - name: TILTAKSPENGER_SOKNAD_API_URL
          value: { { TILTAKSPENGER_SOKNAD_API_URL } }
        - name: NEXT_PUBLIC_TELEMETRY_URL
          value: { { NEXT_PUBLIC_TELEMETRY_URL } }
    ingresses:
        - { { ingress } }
    replicas:
        min: 1
        max: 1
    tokenx:
        enabled: true
    accessPolicy:
        outbound:
            rules:
                - application: tiltakspenger-soknad-api
    idporten:
        enabled: true
        sidecar:
            enabled: true
            level: Level4
            autoLogin: true
