apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspengesoknad
  namespace: tpts
  labels:
    team: tpts
spec:
  image: {{ image }}
  port: 3000
  env:
      - name: TILTAKSPENGESOKNAD_API_URL
        value: {{ TILTAKSPENGESOKNAD_API_URL }}
  ingresses:
    - {{ ingress }}
  replicas:
    min: 1
    max: 1
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - tiltakspengesoknad-api
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
