apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: tiltakspenger-soknad
  namespace: tpts
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: tiltakspenger
  secretName: tiltakspenger-soknad-unleash-secrets
  environment: {{ unleash.environment }}
