name: Deploy dev applications

on:
  workflow_call:

jobs:
  build:
    name: Build and push
    uses: ./.github/workflows/.build-app.yml
    permissions:
      contents: read
      id-token: write
    with:
      ENV: dev
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}

  build-demo:
    name: Build and push demo app
    uses: ./.github/workflows/.build-app.yml
    permissions:
      contents: read
      id-token: write
    with:
      ENV: demo
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}

  deploy:
    name: Deploy to NAIS (dev)
    needs: [ build ]
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build.outputs.IMAGE }}

  deploy-demo:
    name: Deploy to NAIS (dev-demo)
    needs: [ build-demo ]
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: dev
      IMAGE: ${{ needs.build-demo.outputs.IMAGE }}
      NAIS_RESOURCES: '.nais/nais-demo.yml'
