name: Build, push, and deploy to prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/.run-tests.yml
    permissions:
      contents: read
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  build-prod:
    name: Build and push
    uses: ./.github/workflows/.build-app.yml
    permissions:
      contents: read
      id-token: write
    with:
      ENV: prod
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}

  deploy-prod:
    name: Deploy to NAIS (prod)
    needs: [test, build-prod]
    uses: ./.github/workflows/.deploy-to-nais.yml
    permissions:
      contents: read
      id-token: write
    with:
      NAIS_ENV: prod
      IMAGE: ${{ needs.build-prod.outputs.IMAGE }}

  build-and-deploy-dev:
    name: Build and deploy to dev
    needs: [test]
    uses: ./.github/workflows/.deploy-dev-apps.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
