name: Build, push, and deploy to dev (manual)

on:
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/.run-tests.yml
    permissions:
      contents: read
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  build-and-deploy:
    name: Build and deploy to dev
    uses: ./.github/workflows/.deploy-dev-apps.yml
    permissions:
      contents: read
      id-token: write
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
