name: Test/build on feature branch push

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/.run-tests.yml
    permissions:
      contents: read
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  build:
    name: Build app
    uses: ./.github/workflows/.build-app.yml
    permissions:
      contents: read
      id-token: write
    with:
      ENV: dev
      buildImage: false
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_VARSEL_WEBHOOK_URL: ${{ secrets.SLACK_VARSEL_WEBHOOK_URL }}
